unit contextCode;

interface

const
  LCX_NULL = $0;
  LCX_HEAP = $1;
  LCX_CLUSTERED = $2;
  LCX_INDEX_LEAF = $3;
  LCX_INDEX_INTERIOR = $4;
  LCX_TEXT_MIX = $5;
  LCX_TEXT_TREE = $6;
  LCX_DIAGNOSTICS = $7;
  LCX_GAM = $8;
  LCX_SGAM = $9;
  LCX_IAM = $A;
  LCX_PFS = $B;
  LCX_IDENTITY_VALUE = $C;
  LCX_OBJECT_ID = $D;
  LCX_NONSYS_SPLIT = $E;
  LCX_FILE_HEADER = $11;
  LCX_SCHEMA_VERSION = $12;
  LCX_MARK_AS_GHOST = $13;
  LCX_BOOT_PAGE = $14;
  LCX_SYSCONFIG_PAGE = $15;
  LCX_BOOT_PAGE_CKPT = $17;
  LCX_DIFF_MAP = $18;
  LCX_ML_MAP = $19;
  LCX_REMOVE_VERSION_INFO = $1A;
  LCX_DBCC_FORMATTED = $1B;
  LCX_UNLINKED_REORG_PAGE = $1C;
  LCX_BULK_OPERATION_PAGE = $1D;
  LCX_TRACKED_XDES = $1E;
  LCX_ENCRYPT_UNALLOC_PAGE = $1F;
  LCX_SORT_PAGE = $20;
  LCX_WORK_FILE_PAGE = $21;
  LCX_RESTORE_BAD_UNALLOC_PAGE = $22;

implementation

end.

