unit OpCode;

interface

const
  LOP_NULL = $0;
  LOP_FORMAT_PAGE = $1;
  LOP_INSERT_ROWS = $2;
  LOP_DELETE_ROWS = $3;
  LOP_MODIFY_ROW = $4;
  LOP_MODIFY_HEADER = $5;
  LOP_MODIFY_COLUMNS = $6;
  LOP_SET_BITS = $7;
  LOP_SET_FREE_SPACE = $A;
  LOP_DELETE_SPLIT = $B;
  LOP_UNDO_DELETE_SPLIT = $C;
  LOP_EXPUNGE_ROWS = $D;
  LOP_FILE_HDR_MODIFY = $10;
  LOP_CLEAR_GAM_BITS = $11;
  LOP_COUNT_DELTA = $12;
  LOP_ROOT_CHANGE = $13;
  LOP_COMPRESSION_INFO = $14;
  LOP_ENCRYPT_PAGE = $15;
  LOP_INSYSXACT = $16;
  LOP_REMOVE_VERSION_INFO = $7E;
  LOP_BEGIN_XACT = $80;
  LOP_COMMIT_XACT = $81;
  LOP_ABORT_XACT = $82;
  LOP_PREP_XACT = $83;
  LOP_MARK_SAVEPOINT = $84;
  LOP_FORGET_XACT = $85;
  LOP_CREATE_FILE = $86;
  LOP_DROP_FILE = $87;
  LOP_HOBT_DDL = $89;
  LOP_IDENT_NEWVAL = $8A;
  LOP_IDENT_SENTVAL = $8B;
  LOP_HOBT_DELTA = $8C;
  LOP_LOCK_XACT = $8D;
  LOP_CREATE_STREAMFILE = $8E;
  LOP_MIGRATE_LOCKS = $8F;
  LOP_DROP_STREAMFILE = $90;
  LOP_FS_DOWNLEVEL_OP = $91;
  LOP_MODIFY_STREAMFILE_HDR = $92;
  LOP_BP_DBVER = $94;
  LOP_COPY_VERSION_INFO = $95;
  LOP_BEGIN_CKPT = $96;
  LOP_XACT_CKPT = $98;
  LOP_END_CKPT = $99;
  LOP_BUF_WRITE = $9A;
  LOP_BEGIN_RECOVERY = $A0;
  LOP_END_RECOVERY = $A1;
  LOP_TENANT_LOG = $A2;
  LOP_FEDTM_INFO = $A6;
  LOP_CREATE_INDEX = $AD;
  LOP_DROP_INDEX = $AE;
  LOP_CREATE_ALLOCCHAIN = $B0;
  LOP_CREATE_FTCAT = $B4;
  LOP_DROP_FTCAT = $B5;
  LOP_REPL_COMMAND = $C8;
  LOP_BEGIN_UPDATE = $C9;
  LOP_END_UPDATE = $CA;
  LOP_TEXT_POINTER = $CB;
  LOP_TEXT_INFO_BEGIN = $CC;
  LOP_TEXT_INFO_END = $CD;
  LOP_REPL_NOOP = $CE;
  LOP_TEXT_VALUE = $CF;
  LOP_SHRINK_NOOP = $D3;
  LOP_FILESTREAM_INFO_BEGIN = $D4;
  LOP_FILESTREAM_INFO_END = $D5;
  LOP_BULK_EXT_ALLOCATION = $D6;
  LOP_SECURITY_OP = $D7;
  LOP_PAGE_REENCRYPT = $D8;
  LOP_CREATE_PHYSICAL_FILE = $D9;
  LOP_RANGE_INSERT = $DC;
  LOP_INVALIDATE_CACHE = $DD;
  LOP_CSI_ROWGROUP = $DF;
  LOP_HK = $E6;
  LOP_HK_CHECKPOINT = $E7;
  LOP_HK_CHAINED = $E8;
  LOP_SEREPL_MSG = $F0;

implementation

end.

